"""Seed data for GiftXpert categories and products."""
import uuid

# High quality Unsplash/Pexels imagery curated per category
_IMG = {
    "hero_1": "https://images.unsplash.com/photo-1647541706162-f5ad608dd421?auto=format&fit=crop&w=1600&q=80",
    "hero_2": "https://images.unsplash.com/photo-1773450970959-cef81e9b1053?auto=format&fit=crop&w=1600&q=80",
    "employee": "https://images.unsplash.com/photo-1637904731042-2ef367b8c00c?auto=format&fit=crop&w=1200&q=80",
    "client": "https://images.unsplash.com/photo-1760602672748-6a570286ce73?auto=format&fit=crop&w=1200&q=80",
    "festive": "https://images.unsplash.com/photo-1607344645866-009c320b63e0?auto=format&fit=crop&w=1200&q=80",
    "promotional": "https://images.unsplash.com/photo-1719622144274-2408ecf6f6d9?auto=format&fit=crop&w=1200&q=80",
    "welcome": "https://images.unsplash.com/photo-1608528577891-eb055944b2e7?auto=format&fit=crop&w=1200&q=80",
    "reward": "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1200&q=80",
    "eco": "https://images.pexels.com/photos/31438304/pexels-photo-31438304.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "luxury": "https://images.unsplash.com/photo-1549049950-48d5887197a0?auto=format&fit=crop&w=1200&q=80",
    "wellness": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80",
    # Product imagery pool
    "p_hamper_1": "https://images.unsplash.com/photo-1608755728617-aefab37d2edd?auto=format&fit=crop&w=1000&q=80",
    "p_hamper_2": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1000&q=80",
    "p_bottle": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1000&q=80",
    "p_notebook": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80",
    "p_pen": "https://images.unsplash.com/photo-1583485088034-697b5bc36b92?auto=format&fit=crop&w=1000&q=80",
    "p_diary": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1000&q=80",
    "p_mug": "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1000&q=80",
    "p_bag": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80",
    "p_watch": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=80",
    "p_tea": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1000&q=80",
    "p_wine": "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?auto=format&fit=crop&w=1000&q=80",
    "p_chocolate": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=1000&q=80",
    "p_plant": "https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=1000&q=80",
    "p_cap": "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1000&q=80",
    "p_tshirt": "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=1000&q=80",
    "p_leather": "https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=1000&q=80",
    "p_perfume": "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1000&q=80",
    "p_candle": "https://images.unsplash.com/photo-1602874801007-aa5c65ee34cc?auto=format&fit=crop&w=1000&q=80",
    "p_speaker": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1000&q=80",
    "p_powerbank": "https://images.unsplash.com/photo-1609592424823-d81c6d5d2d3b?auto=format&fit=crop&w=1000&q=80",
    "p_trophy": "https://images.unsplash.com/photo-1583511655802-41799bd57d8b?auto=format&fit=crop&w=1000&q=80",
    "p_yoga": "https://images.unsplash.com/photo-1588286840104-8957b019727f?auto=format&fit=crop&w=1000&q=80",
    "p_backpack": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80",
    "p_bamboo": "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=80",
}


CATEGORIES = [
    {
        "id": str(uuid.uuid4()),
        "slug": "employee-gifting",
        "name": "Employee Gifting",
        "description": "Celebrate your team with thoughtfully curated gifts for every milestone — joining, festivals, anniversaries, and achievements.",
        "image": _IMG["employee"],
        "icon": "users",
        "subcategories": [
            {"slug": "joining-kits", "name": "Joining Kits", "description": "Warm, branded welcome kits for new hires."},
            {"slug": "work-anniversary", "name": "Work Anniversary Gifts", "description": "Commemorate tenure with premium keepsakes."},
            {"slug": "performance-rewards", "name": "Performance Rewards", "description": "Recognise high performers with curated boxes."},
            {"slug": "festive-gifts-employees", "name": "Festive Gifts", "description": "Diwali, New Year and seasonal hampers."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "client-gifting",
        "name": "Client / Customer Gifting",
        "description": "Strengthen client relationships with sophisticated, brand-forward gifts that leave a lasting impression.",
        "image": _IMG["client"],
        "icon": "handshake",
        "subcategories": [
            {"slug": "festive-client", "name": "Festive Gifts", "description": "Premium client hampers for festivals."},
            {"slug": "thank-you", "name": "Thank You Gifts", "description": "Elegant gestures of appreciation."},
            {"slug": "executive-gifts", "name": "Executive Gifts", "description": "Curated gifts for senior stakeholders."},
            {"slug": "event-gifts", "name": "Event Giveaways", "description": "Branded gifts for client events."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "festive-gifting",
        "name": "Festive & Seasonal Gifting",
        "description": "Celebrate every occasion — Diwali, New Year, Rakhi and more — with beautifully designed seasonal hampers.",
        "image": _IMG["festive"],
        "icon": "sparkles",
        "subcategories": [
            {"slug": "diwali", "name": "Diwali Hampers", "description": "Curated Diwali gifting collections."},
            {"slug": "new-year", "name": "New Year Gifts", "description": "Start the year with premium gifting."},
            {"slug": "holi", "name": "Holi Specials", "description": "Colourful, festive hampers."},
            {"slug": "christmas", "name": "Christmas Gifts", "description": "Warm holiday curations."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "promotional-gifts",
        "name": "Promotional / Branding Gifts",
        "description": "Amplify brand recall with custom-branded merchandise, giveaways and promotional essentials.",
        "image": _IMG["promotional"],
        "icon": "megaphone",
        "subcategories": [
            {"slug": "branded-merch", "name": "Branded Merchandise", "description": "Custom branded essentials."},
            {"slug": "conference-giveaways", "name": "Conference Giveaways", "description": "Branded gifts for events & expos."},
            {"slug": "apparel", "name": "Apparel", "description": "Corporate t-shirts, caps, jackets."},
            {"slug": "tech-promotional", "name": "Tech Gadgets", "description": "Branded electronics & accessories."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "welcome-kits",
        "name": "Welcome / Onboarding Kits",
        "description": "Delight new hires from day one with beautifully curated onboarding kits and swag.",
        "image": _IMG["welcome"],
        "icon": "gift",
        "subcategories": [
            {"slug": "essentials", "name": "Essentials Kits", "description": "Everyday workplace essentials."},
            {"slug": "remote-kits", "name": "Remote Work Kits", "description": "For distributed teams."},
            {"slug": "premium-onboarding", "name": "Premium Onboarding", "description": "Executive-grade kits."},
            {"slug": "stationery-kits", "name": "Stationery Kits", "description": "Notebooks, pens, planners."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "reward-recognition",
        "name": "Reward & Recognition Gifts",
        "description": "Recognise achievements with premium trophies, plaques and reward boxes that inspire excellence.",
        "image": _IMG["reward"],
        "icon": "trophy",
        "subcategories": [
            {"slug": "trophies", "name": "Trophies & Plaques", "description": "Custom engraved recognition awards."},
            {"slug": "milestone", "name": "Milestone Gifts", "description": "Years-of-service recognitions."},
            {"slug": "top-performer", "name": "Top Performer Boxes", "description": "Luxury boxes for leaders."},
            {"slug": "instant-rewards", "name": "Instant Rewards", "description": "Spot recognition gifts."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "sustainable-gifting",
        "name": "Sustainable / Eco-Friendly Gifting",
        "description": "Premium gifts with a conscience — plantable, recycled and sustainably sourced corporate gifting.",
        "image": _IMG["eco"],
        "icon": "leaf",
        "subcategories": [
            {"slug": "plantable", "name": "Plantable Gifts", "description": "Seed-based, plantable merchandise."},
            {"slug": "bamboo", "name": "Bamboo & Wood", "description": "Natural material products."},
            {"slug": "recycled", "name": "Recycled Products", "description": "Made from recycled materials."},
            {"slug": "organic", "name": "Organic Kits", "description": "Natural, organic curations."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "luxury-gifting",
        "name": "Luxury & Premium Gifting",
        "description": "Sophisticated, elegant gifts for leadership, VIP clients and stakeholder appreciation.",
        "image": _IMG["luxury"],
        "icon": "crown",
        "subcategories": [
            {"slug": "executive-luxury", "name": "Executive Luxury", "description": "Premium leather, watches, perfumes."},
            {"slug": "wine-hampers", "name": "Wine & Gourmet", "description": "Imported wines and gourmet foods."},
            {"slug": "leather-goods", "name": "Leather Goods", "description": "Handcrafted leather accessories."},
            {"slug": "custom-luxury", "name": "Custom Luxury Boxes", "description": "Bespoke curations."},
        ],
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "wellness-gifting",
        "name": "Wellness & Lifestyle Gifting",
        "description": "Gifts that promote health, mindfulness and work-life balance — perfect for modern employees.",
        "image": _IMG["wellness"],
        "icon": "heart",
        "subcategories": [
            {"slug": "yoga-kits", "name": "Yoga & Fitness Kits", "description": "Mats, bottles, resistance bands."},
            {"slug": "aromatherapy", "name": "Aromatherapy Sets", "description": "Candles, diffusers, oils."},
            {"slug": "self-care", "name": "Self-Care Boxes", "description": "Skincare & wellness bundles."},
            {"slug": "healthy-snacks", "name": "Healthy Snack Boxes", "description": "Nuts, teas, organic snacks."},
        ],
    },
]


def _p(slug, name, cat, sub, short, desc, features, specs, cust, moq, price, imgs):
    return {
        "id": str(uuid.uuid4()),
        "slug": slug,
        "name": name,
        "category_slug": cat,
        "subcategory_slug": sub,
        "short_description": short,
        "description": desc,
        "features": features,
        "specifications": specs,
        "customization": cust,
        "moq": moq,
        "price_range": price,
        "images": imgs,
    }


PRODUCTS = [
    # Employee Gifting - Joining Kits
    _p("premium-joining-kit", "Premium Joining Kit", "employee-gifting", "joining-kits",
       "A curated welcome kit featuring notebook, pen, bottle, t-shirt and more.",
       "Impress new hires from day one with this premium joining kit. Carefully curated to include everyday essentials branded with your logo, packaged in an elegant gift box.",
       ["Leather-finish diary", "Metal pen", "Insulated bottle", "Branded t-shirt", "Custom welcome card"],
       ["Box dimensions: 30x25x10 cm", "Material: Recycled craft board", "Weight: ~1.2 kg"],
       "Logo printing, embossing, custom welcome card, gift tag personalisation.",
       "25 units", "₹1,800 – ₹3,500",
       [_IMG["p_hamper_1"], _IMG["p_notebook"], _IMG["p_pen"]]),

    _p("executive-onboarding-box", "Executive Onboarding Box", "employee-gifting", "joining-kits",
       "Leather-bound essentials for senior hires and executives.",
       "An executive-grade onboarding kit with a leather journal, premium pen set, branded bottle and a signature welcome letter.",
       ["Genuine leather journal", "Parker pen", "Copper bottle", "Silk pouch", "Embossed card"],
       ["Leather: Full-grain", "Bottle: 750ml copper", "Delivered in wooden box"],
       "Name embossing, logo debossing, custom welcome note.",
       "15 units", "₹4,500 – ₹8,500",
       [_IMG["p_leather"], _IMG["p_diary"], _IMG["p_bottle"]]),

    # Employee - Work Anniversary
    _p("anniversary-trophy-box", "Anniversary Recognition Box", "employee-gifting", "work-anniversary",
       "Commemorate years of service with an engraved trophy and curated keepsakes.",
       "A recognition box that celebrates tenure milestones with an engraved crystal trophy, thank-you card, and premium accessories.",
       ["Crystal trophy with engraving", "Personalised card", "Premium chocolate selection", "Branded pen"],
       ["Trophy: 20cm crystal", "Box: Velvet-lined", "Custom engraving included"],
       "Years of service engraving, name, date, company logo.",
       "10 units", "₹2,500 – ₹4,500",
       [_IMG["p_trophy"], _IMG["p_chocolate"], _IMG["p_pen"]]),

    # Employee - Performance Rewards
    _p("top-performer-luxury-box", "Top Performer Luxury Box", "employee-gifting", "performance-rewards",
       "A luxurious reward box for top performers — watch, perfume, chocolates & more.",
       "Recognise top talent with a luxury reward box including a premium watch, designer perfume, gourmet chocolates, and a handwritten thank-you card.",
       ["Branded analog watch", "Designer perfume 100ml", "Imported chocolates", "Leather card holder"],
       ["Watch: Stainless steel", "Perfume: Eau de Parfum", "Presentation box included"],
       "Personalised message card, watch engraving available.",
       "20 units", "₹5,500 – ₹9,000",
       [_IMG["p_watch"], _IMG["p_perfume"], _IMG["p_chocolate"]]),

    # Employee - Festive
    _p("diwali-employee-hamper", "Diwali Employee Hamper", "employee-gifting", "festive-gifts-employees",
       "A festive Diwali hamper with sweets, dry fruits, diyas and premium packaging.",
       "Celebrate Diwali with your employees through a beautifully designed hamper featuring artisanal sweets, dry fruits, decorative diyas, and a branded greeting card.",
       ["Assorted sweets 500g", "Premium dry fruits 500g", "Hand-painted diyas", "Greeting card"],
       ["Packaged in a wooden gift box", "Shelf life: 60 days", "Vegetarian"],
       "Logo on box, custom greeting message, ribbon colour.",
       "50 units", "₹900 – ₹2,200",
       [_IMG["p_hamper_2"], _IMG["p_chocolate"]]),

    # Client Gifting
    _p("client-festive-hamper", "Client Festive Hamper", "client-gifting", "festive-client",
       "An elegant festive hamper curated for valued clients.",
       "A premium festive hamper for clients featuring imported chocolates, artisanal teas, a scented candle, and a branded thank-you note.",
       ["Imported Belgian chocolates", "Single-origin tea", "Scented soy candle", "Thank-you card"],
       ["Box: Premium rigid card", "Ribbon: Satin", "Vegetarian options available"],
       "Co-branded card, logo ribbon, custom greeting.",
       "25 units", "₹2,200 – ₹4,500",
       [_IMG["p_hamper_1"], _IMG["p_tea"], _IMG["p_candle"]]),

    _p("executive-wine-hamper", "Executive Wine & Gourmet Hamper", "client-gifting", "executive-gifts",
       "Imported wine paired with gourmet chocolates and artisanal snacks.",
       "An executive-level client gift featuring a premium imported wine, gourmet chocolates, artisanal cheese crackers, and a wooden presentation box.",
       ["Imported wine 750ml", "Belgian truffles", "Artisanal crackers", "Wooden presentation box"],
       ["Wine: Cabernet / Chardonnay options", "Wood box: Walnut finish"],
       "Engraved wooden box, personalised note, gift wrapping.",
       "10 units", "₹4,500 – ₹8,500",
       [_IMG["p_wine"], _IMG["p_chocolate"], _IMG["p_hamper_1"]]),

    _p("thank-you-box-classic", "Classic Thank-You Box", "client-gifting", "thank-you",
       "A simple, elegant thank-you gift for clients and partners.",
       "A refined thank-you gift featuring a handwritten card, gourmet chocolates, a scented candle, and a branded keepsake.",
       ["Handwritten card", "Gourmet chocolates", "Scented candle", "Brand keepsake"],
       ["Box: Kraft with foil stamping", "Eco-friendly packaging"],
       "Handwritten messages, logo debossing, custom card copy.",
       "15 units", "₹1,200 – ₹2,500",
       [_IMG["p_candle"], _IMG["p_chocolate"]]),

    _p("event-branded-gift", "Event Branded Gift Set", "client-gifting", "event-gifts",
       "A compact, branded giveaway for client events and conferences.",
       "A sleek branded gift set for client events featuring a premium notebook, pen, and tote bag — designed to leave a lasting impression.",
       ["Leather-finish notebook", "Metal pen", "Canvas tote bag"],
       ["Notebook: A5, 120 gsm pages", "Tote: Heavy canvas"],
       "Logo printing, custom colours, bundle options.",
       "50 units", "₹650 – ₹1,200",
       [_IMG["p_notebook"], _IMG["p_bag"], _IMG["p_pen"]]),

    # Festive
    _p("diwali-premium-hamper", "Diwali Premium Hamper", "festive-gifting", "diwali",
       "A premium Diwali hamper with sweets, chocolates, diyas and gifts.",
       "A beautifully curated Diwali hamper featuring premium sweets, imported chocolates, hand-painted diyas, dry fruits, and a custom greeting card.",
       ["Premium sweets 750g", "Imported chocolates", "Hand-painted diyas", "Dry fruits 500g"],
       ["Packaged in festive gift box", "Shelf life: 60 days"],
       "Custom greeting card, logo on box, ribbon customisation.",
       "50 units", "₹1,500 – ₹3,500",
       [_IMG["p_hamper_2"], _IMG["p_chocolate"]]),

    _p("new-year-wellness-hamper", "New Year Wellness Hamper", "festive-gifting", "new-year",
       "Start the year right with a wellness-focused New Year hamper.",
       "A mindful New Year hamper featuring organic teas, wellness journal, aromatherapy candle, and healthy snack selection.",
       ["Organic tea set", "Wellness journal", "Aromatherapy candle", "Healthy snacks"],
       ["Eco-friendly packaging", "Organic certified"],
       "Logo printing, custom journal cover, branded card.",
       "25 units", "₹1,800 – ₹3,200",
       [_IMG["p_tea"], _IMG["p_candle"], _IMG["p_diary"]]),

    _p("christmas-gift-basket", "Christmas Gourmet Basket", "festive-gifting", "christmas",
       "A warm Christmas hamper with gourmet foods and festive decor.",
       "A gourmet Christmas basket featuring artisanal chocolates, mulled wine kit, cookies, and festive decor items.",
       ["Artisanal chocolates", "Mulled wine kit", "Gourmet cookies", "Festive decor"],
       ["Basket: Wicker", "Alcohol: Optional"],
       "Custom ribbon, logo placement, personalised tag.",
       "20 units", "₹2,200 – ₹4,500",
       [_IMG["p_hamper_1"], _IMG["p_chocolate"], _IMG["p_wine"]]),

    # Promotional
    _p("branded-bottle-set", "Branded Insulated Bottle Set", "promotional-gifts", "branded-merch",
       "Stainless steel insulated bottles with premium logo branding.",
       "A set of premium stainless steel insulated bottles, perfect for large-scale promotional campaigns. Keeps beverages hot for 12 hours and cold for 24.",
       ["Double-wall insulation", "Leak-proof cap", "Laser engraving option", "500ml / 750ml sizes"],
       ["Material: 304 stainless steel", "Capacity: 500ml / 750ml", "Colours: 6 options"],
       "Laser engraving, screen printing, UV printing, custom colours.",
       "100 units", "₹450 – ₹950",
       [_IMG["p_bottle"]]),

    _p("branded-notebook-pen", "Branded Notebook & Pen Combo", "promotional-gifts", "branded-merch",
       "Premium notebook paired with a metal pen — ideal promotional combo.",
       "A classic promotional combo featuring a leather-finish notebook with 160 pages and a premium metal pen in a gift box.",
       ["160 pages 100gsm", "Metal pen with refill", "Magnetic closure notebook", "Gift box"],
       ["Notebook: A5", "Pen: Roller ball, metal"],
       "Logo debossing on notebook, laser engraving on pen, custom box sleeve.",
       "100 units", "₹350 – ₹750",
       [_IMG["p_notebook"], _IMG["p_pen"]]),

    _p("conference-welcome-bag", "Conference Welcome Bag", "promotional-gifts", "conference-giveaways",
       "A ready-to-distribute conference welcome bag with essentials.",
       "A conference-ready welcome bag including a branded tote, notebook, pen, bottle, and lanyard — perfect for events and expos.",
       ["Canvas tote bag", "Notebook + pen", "Insulated bottle", "Lanyard & ID holder"],
       ["Tote: 12oz canvas", "Notebook: A5"],
       "Full custom branding across all items, bag colour options.",
       "200 units", "₹650 – ₹1,250",
       [_IMG["p_bag"], _IMG["p_bottle"], _IMG["p_notebook"]]),

    _p("branded-tshirt", "Custom Branded T-Shirt", "promotional-gifts", "apparel",
       "Premium cotton t-shirts with full customisation options.",
       "High-quality cotton t-shirts ideal for team uniforms, events, and promotional merchandise. Available in multiple colours, sizes and printing methods.",
       ["100% combed cotton", "Available in 10 colours", "Sizes XS–3XL", "Screen / DTG printing"],
       ["Fabric: 180 GSM", "Cut: Regular / Fitted"],
       "Screen printing, embroidery, DTG printing, custom labels.",
       "50 units", "₹280 – ₹650",
       [_IMG["p_tshirt"]]),

    _p("branded-cap", "Branded Cap", "promotional-gifts", "apparel",
       "Embroidered caps for corporate events and teams.",
       "Classic 6-panel structured caps with premium embroidery — perfect for brand visibility at events, sports days, and corporate outings.",
       ["6-panel structured cap", "Embroidery or patch", "Adjustable strap", "8 colour options"],
       ["Material: Cotton twill", "One size fits most"],
       "Embroidery, patch, full colour printing.",
       "100 units", "₹220 – ₹450",
       [_IMG["p_cap"]]),

    _p("wireless-speaker-branded", "Wireless Bluetooth Speaker", "promotional-gifts", "tech-promotional",
       "A branded wireless speaker for premium tech giveaways.",
       "A sleek portable Bluetooth speaker with 10-hour battery life, IPX5 water resistance, and premium sound. Laser engraved with your brand.",
       ["Bluetooth 5.0", "10-hour battery", "IPX5 rated", "Built-in mic"],
       ["Battery: 1200mAh", "Range: 10m", "Colours: 4"],
       "Laser engraving, custom box sleeve, brand colours.",
       "50 units", "₹1,200 – ₹2,500",
       [_IMG["p_speaker"]]),

    _p("powerbank-branded", "Branded Powerbank 10000mAh", "promotional-gifts", "tech-promotional",
       "Slim, branded 10,000mAh powerbanks for everyday charging.",
       "High-capacity powerbanks with dual USB output and a slim profile — great for tech-forward promotional campaigns.",
       ["10,000mAh capacity", "Dual USB output", "Type-C input", "LED indicator"],
       ["Dimensions: 14x7x1.5cm", "Weight: 220g"],
       "UV printing, laser engraving, box branding.",
       "100 units", "₹600 – ₹1,200",
       [_IMG["p_powerbank"]]),

    # Welcome Kits
    _p("essentials-welcome-kit", "Essentials Welcome Kit", "welcome-kits", "essentials",
       "Everyday workplace essentials in a single branded box.",
       "A practical welcome kit with workplace essentials including a notebook, pen, bottle, mug and branded tote — all in a premium gift box.",
       ["Notebook + pen", "Insulated bottle", "Ceramic mug", "Tote bag"],
       ["Box: Rigid", "Items: 5 essentials"],
       "Logo on all items, custom welcome card, box branding.",
       "25 units", "₹1,200 – ₹2,500",
       [_IMG["p_hamper_1"], _IMG["p_mug"], _IMG["p_notebook"]]),

    _p("remote-work-kit", "Remote Work Kit", "welcome-kits", "remote-kits",
       "A thoughtful kit for remote and hybrid employees.",
       "Designed for distributed teams — features a premium mousepad, noise-cancelling headphones, webcam cover, and branded notebook.",
       ["Premium mousepad", "Bluetooth headphones", "Webcam cover", "Notebook"],
       ["Headphones: Over-ear, wireless"],
       "Logo printing across items, custom shipping box.",
       "30 units", "₹2,500 – ₹4,800",
       [_IMG["p_speaker"], _IMG["p_notebook"]]),

    _p("premium-onboarding-kit", "Premium Onboarding Kit", "welcome-kits", "premium-onboarding",
       "An executive-grade onboarding kit for senior hires.",
       "A luxury onboarding kit featuring a leather journal, Parker pen, copper bottle, silk pouch, and custom welcome letter — delivered in a wooden presentation box.",
       ["Leather journal", "Parker pen", "Copper bottle", "Silk pouch"],
       ["Box: Walnut wood", "Leather: Full-grain"],
       "Embossing, engraving, handwritten welcome letter.",
       "15 units", "₹4,800 – ₹7,500",
       [_IMG["p_leather"], _IMG["p_diary"]]),

    _p("stationery-kit", "Executive Stationery Kit", "welcome-kits", "stationery-kits",
       "A refined stationery kit with notebook, planner, pens and more.",
       "A complete stationery kit with a premium notebook, weekly planner, executive pen set, sticky notes, and a branded organiser.",
       ["Notebook + planner", "Pen set of 3", "Sticky notes", "Organiser"],
       ["Notebook: A5", "Planner: Weekly"],
       "Logo debossing, custom cover art.",
       "50 units", "₹850 – ₹1,800",
       [_IMG["p_notebook"], _IMG["p_diary"], _IMG["p_pen"]]),

    # Reward & Recognition
    _p("crystal-trophy-custom", "Custom Crystal Trophy", "reward-recognition", "trophies",
       "Engraved crystal trophies for awards and recognition.",
       "Premium crystal trophies with custom 3D engraving — perfect for annual awards, top-performer recognition, and leadership awards.",
       ["3D laser engraving", "Multiple shapes available", "Velvet-lined gift box", "Custom plaque"],
       ["Height: 15–30cm", "Material: Optical crystal"],
       "3D engraving, custom shape, logo, recipient name.",
       "10 units", "₹1,800 – ₹4,500",
       [_IMG["p_trophy"]]),

    _p("milestone-recognition-box", "Milestone Recognition Box", "reward-recognition", "milestone",
       "A celebratory box for years-of-service milestones.",
       "Celebrate years of service with a custom plaque, engraved pen, thank-you letter, and premium chocolates — all in a velvet box.",
       ["Wooden plaque", "Engraved pen", "Thank-you letter", "Chocolates"],
       ["Plaque: Solid wood", "Box: Velvet-lined"],
       "Engraving, personalisation, custom years of service.",
       "15 units", "₹2,500 – ₹4,800",
       [_IMG["p_trophy"], _IMG["p_chocolate"]]),

    # Sustainable
    _p("plantable-seed-kit", "Plantable Seed Kit", "sustainable-gifting", "plantable",
       "Seed-embedded journals, pencils and cards — plantable gifts.",
       "A sustainable gift kit featuring plantable seed paper journals, seed pencils, and greeting cards that bloom into herbs and flowers.",
       ["Seed paper journal", "Plantable pencils (set of 5)", "Seed greeting card", "Grow kit"],
       ["Materials: 100% recycled", "Seeds: Basil, tulsi, marigold"],
       "Custom branding on seed paper, tree-friendly inks.",
       "50 units", "₹450 – ₹950",
       [_IMG["p_plant"], _IMG["p_notebook"]]),

    _p("bamboo-corporate-kit", "Bamboo Corporate Kit", "sustainable-gifting", "bamboo",
       "A beautifully crafted bamboo kit with eco-friendly essentials.",
       "An eco-luxury kit featuring a bamboo notebook, bamboo pen, bamboo water bottle, and a jute tote bag — all presented in a recycled kraft box.",
       ["Bamboo notebook", "Bamboo pen", "Bamboo bottle", "Jute tote"],
       ["Material: FSC-certified bamboo", "Packaging: Kraft"],
       "Laser engraving on bamboo, screen printing on jute.",
       "30 units", "₹950 – ₹1,800",
       [_IMG["p_bamboo"], _IMG["p_bag"]]),

    _p("recycled-gift-set", "Recycled Materials Gift Set", "sustainable-gifting", "recycled",
       "Gifts crafted from 100% recycled materials.",
       "A thoughtful gift set including a recycled PET bottle, recycled paper notebook, recycled cotton tote, and a branded recycled-card gift box.",
       ["Recycled PET bottle", "Recycled notebook", "Recycled cotton tote", "Branded box"],
       ["Recycled content: 100%"],
       "Screen printing, logo on all items.",
       "50 units", "₹750 – ₹1,500",
       [_IMG["p_bottle"], _IMG["p_notebook"], _IMG["p_bag"]]),

    # Luxury
    _p("executive-leather-portfolio", "Executive Leather Portfolio", "luxury-gifting", "leather-goods",
       "A full-grain leather portfolio for executive gifting.",
       "A handcrafted full-grain leather portfolio with magnetic closure, A4 notepad holder, multiple card slots, and a premium pen loop.",
       ["Full-grain leather", "A4 notepad included", "8 card slots", "Pen loop"],
       ["Dimensions: 35x27cm", "Colours: Tan, Black, Brown"],
       "Personalised embossing, gold-foil initials.",
       "10 units", "₹3,800 – ₹6,500",
       [_IMG["p_leather"]]),

    _p("luxury-wine-gift", "Luxury Imported Wine Gift Box", "luxury-gifting", "wine-hampers",
       "Imported wine, artisanal chocolates, and a wooden gift box.",
       "A luxurious wine gift featuring a premium imported wine, Belgian truffles, artisanal crackers, and a walnut wood presentation box with engraving.",
       ["Imported wine 750ml", "Belgian truffles", "Artisanal crackers", "Walnut box"],
       ["Wine options: Cabernet, Chardonnay, Merlot"],
       "Custom wine labels, engraved wooden box.",
       "10 units", "₹5,500 – ₹9,500",
       [_IMG["p_wine"], _IMG["p_chocolate"]]),

    _p("luxury-perfume-set", "Luxury Perfume Gift Set", "luxury-gifting", "executive-luxury",
       "A premium designer perfume set in a gift box.",
       "A designer perfume gift set featuring a 100ml Eau de Parfum, travel atomiser, and scented pouch — presented in a luxurious magnetic-close gift box.",
       ["EDP 100ml", "Travel atomiser 10ml", "Scented pouch"],
       ["Fragrance: Woody / Floral options"],
       "Personalised card, branded outer sleeve.",
       "20 units", "₹3,500 – ₹7,500",
       [_IMG["p_perfume"]]),

    # Wellness
    _p("yoga-wellness-kit", "Yoga & Wellness Kit", "wellness-gifting", "yoga-kits",
       "Yoga mat, bottle, and journal — wellness for employees.",
       "A wellness-focused gift kit with a premium yoga mat, insulated water bottle, wellness journal, and a branded tote — encouraging mindfulness and fitness.",
       ["Premium yoga mat (6mm)", "Insulated bottle", "Wellness journal", "Tote bag"],
       ["Mat: TPE, 6mm thick", "Bottle: 500ml"],
       "Logo printing on mat, branded journal cover.",
       "25 units", "₹1,800 – ₹3,500",
       [_IMG["p_yoga"], _IMG["p_bottle"]]),

    _p("aromatherapy-set", "Aromatherapy Gift Set", "wellness-gifting", "aromatherapy",
       "Scented candles, essential oils and a diffuser for mindful moments.",
       "A curated aromatherapy set featuring a ceramic diffuser, three essential oils (lavender, eucalyptus, sweet orange), and two soy candles in an elegant gift box.",
       ["Ceramic diffuser", "3 essential oils", "2 soy candles", "Gift box"],
       ["Oils: 10ml each", "Diffuser: USB powered"],
       "Custom box, branded scented candle labels.",
       "20 units", "₹1,500 – ₹2,800",
       [_IMG["p_candle"]]),

    _p("healthy-snacks-box", "Healthy Snacks Box", "wellness-gifting", "healthy-snacks",
       "A curated box of organic snacks, nuts, teas and dark chocolates.",
       "A thoughtful wellness box with organic nuts, artisanal teas, dark chocolate, and protein bars — a healthy, delicious gift for teams.",
       ["Organic mixed nuts 500g", "Artisanal tea assortment", "Dark chocolate bars", "Protein bars"],
       ["Organic certified", "Vegetarian", "Shelf life: 90 days"],
       "Custom box branding, personalised note, bundle customisation.",
       "50 units", "₹950 – ₹1,800",
       [_IMG["p_tea"], _IMG["p_chocolate"], _IMG["p_hamper_2"]]),

    _p("self-care-premium-box", "Premium Self-Care Box", "wellness-gifting", "self-care",
       "A luxurious self-care box with skincare, candles and wellness essentials.",
       "A premium self-care box featuring organic skincare products, a scented soy candle, bath salts, and a silk eye mask — perfect for employee wellness.",
       ["Organic skincare set", "Soy candle", "Bath salts", "Silk eye mask"],
       ["Organic certified", "Cruelty-free"],
       "Logo on box, custom wellness card.",
       "25 units", "₹2,200 – ₹4,200",
       [_IMG["p_candle"], _IMG["p_perfume"]]),
]
